using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SolverSubProject.Information;

public enum Reason
{
    // Allowed reasons at bagrut, in order.
    GIVEN,

    ADJACENT_ANGLES_180, // 1
    VERTEX_ANGLES_EQUAL, // 2
    TRIANGLE_EQULA_SIDES_EQUAL_ANGLES, // 3
    ISOSCELES_BASE_ANGLES_EQUAL, // 4
    TRIANGLE_SUM_TWO_SIDES_LARGER_THIRD, // 5
    ISOSCELES_PERPENDICUAL_ANBISECTOR_ANGLE, // 6
    TRIANGLE_ANBISECTOR_PERPENDICULAR_IS_ISOSCELES, // 7
    TRIANGLE_ANBISECTOR_BISECTOR_IS_ISOSCELES, // 8
    TRIANGLE_PERPENDICULAR_BISECTOR_IS_ISOSCELES, // 9
    TRIANGLE_LARGER_SIDE_LARGER_ANGLE, // 10
    TRIANGLE_LARGER_ANGLE_BIGGER_SIDE, // 11
    TRIANGLE_ANGLE_SUM_180, // 12
    OUTSIDE_ANGLE_TWO_OTHER_TRIANGLE_ANGLES, //13
    MIDSEGMENT_PARALLEL_OTHER_TRIANGLE_SIDE, // 14
    LINE_BISECTS_SIDE_PARALLEL_OTHER_BISECTS_THIRD, // 15
    LINE_INTERSECTS_SIDES_PARALLEL_THRID_HALF_THIRD_LENGTH_IS_MIDSEGMENT, // 16
    CONGRUENT_S_A_S, // 17
    CONGRUENT_A_S_A, // 18
    CONGRUENT_S_S_S, // 19
    CONGRUENT_S_S_A, // 20
    KITE_MAIN_DIAGONAL_BISECTS_ANGLE_BISECTS_DIAGONAL, // 21
    CORRESPONDING_ANGLES_EQUAL_LINES_PARALLEL, // 22
    ALTERNATE_ANGLES_EQUAL_LINES_PARALLEL, // 23
    COINTERIOR_ANGLES_180_LINES_PARALLEL, // 24
    CORRESPONDING_ANGLES_EQUAL, // 25 A
    ALTERNATE_ANGLES_EQUAL, // 25 A
    COINTERIOR_ANGLES_180, // 25 A
    PARALLELOGRAM_OPPOSITE_ANGLES_EQUAL, // 26
    PARALLELOGRAM_OPPOSITE_SIDES_EQUAL, // 27
    PARALLELOGRAM_DIAGONALS_BISECT_EACH_OTHER, // 28
    QUAD_OPPOSIDE_ANGLES_EQUAL_PARALLELOGRAM, // 29
    QUAD_OPPOSIDE_SIDES_EQUAL_PARALLELOGRAM, // 30
    QUAD_OPPOSITE_PAIR_PARALLEL_EQUAL_PARALLELOGRAM, // 31
    QUAD_DIAGONALS_BISECT_EACH_OTHER_PARALLELOGRAM, // 32
    RHOMBUS_DIAGONALS_BISECT_EACH_OTHER, // 33
    PARALLELOGRAM_DIAGONAL_ANGLE_BISECTOR_RHOMBUS, // 34
    RHOMBUS_DIAGONALS_PERPENDICULAR, // 35
    PARALLELOGRAM_DIAGONALS_PERPENDICULAR_RHOMBUS, // 36
    RECTANGLE_DIAGONALS_EQUAL, // 37
    PARALLELOGRAM_DIAGONALS_EQUAL_RECTANGLE, // 38
    ISOSTRAPEZOID_BASE_ANGLES_EQUAL, // 39
    TRAPEZOID_BASE_ANGLES_EQUAL_ISOSTRAPEZOID, // 40
    ISOSTRAPEZOID_DIAGONALS_EQUAL, // 41
    TRAPEZOID_DIAGONALS_EQUAL_ISOSTRAPEZOID, // 42
    TRAPEZOID_MIDSEGMENT_PARALLEL_BASES_EQUAL_BASE_AVERAGE, // 43
    TRAPEZOID_LINE_BISECTS_SIDE_PARALLEL_BASES_IS_MIDSEGMENT, // 44
    TRIANGLE_BISECTORS_INTERSECT, // 45
    TRIANGLE_BISECTORS_INTERSECT_RATIO_1_FAR_2_CLOSE, // 46
    POINT_ON_ANBISECTOR_EQUAL_DISTANCE_TO_SIDES, // 47
    POINT_IN_EQUAL_DISTANCE_TO_SIDES_IS_ON_ANBISECTOR, // 48
    TRIANGLES_ANBISECTORS_INTERSECT_INCIRCLE_CENTER, // 49
    EVERY_TRIANGLE_HAS_INCIRCLE, // 50
    POINT_ON_PERPENDICULARBISECTOR_EQUAL_DISTANCE_TO_SIDE_VERTICES, // 51
    POINT_AT_EQUAL_DISTANCE_FROM_SIDE_VERTICES_IS_ON_PERPENDICULARBISECTOR, // 52
    EVERY_TRAANGLE_HAS_CIRCUMCIRCLE, // 53
    TRIANGLE_PERPENDICULARBISECTORS_INTERSECT_CIRCUMCIRCLE_CENTER, // 54
    TRIANGLE_PERPENDICULARS_INTERSECT_ONE_POINT, // 55
    QUAD_HAS_CIRCUMCIRCLE_IF_OPPOSITE_ANGLES_180, // 56
    CONVEX_QUAD_HAS_INCIRCLE_IF_OPPOSITE_SIDES_SUM_EQUAL, // 57
    POLYGON_HAS_CIRCUMCIRCLE, // 58
    POLYGON_HAS_INCIRCLE, // 59
    THREE_POINTS_ARE_ON_SINGLE_CIRCLE, // 60
    EQUAL_ARCS_EQUAL_CENTERALANGLES, // 61
    EQUAL_CHORDS_EQUAL_CENTERALANGLES, // 62
    EQUAL_ARCS_EQUAL_CHORDS, // 63
    EQUAL_CHORDS_EQUAL_DISTANCE_TO_CENTER, // 64
    EQUAL_DISTANCE_TO_CENTER_EQUAL_CHORDS, // 65
    CHORD_SIZE_DEPENDS_ON_CHORD_DISTANCE_TO_CENTER, // 66
    PERPENDICULAR_FROM_CENTER_TO_CHORD_BISECTS_CHORD_BISECTS_CENTRALANGLE_BISECTS_ARC, // 67
    LINE_FROM_CIRCLE_CENTER_INTERSECTS_CHORD_PERPENDICULAR_CHORD, // 68
    PERIPHERALANGLE_EQUAL_HALF_CENTERALANGLE, // 69
    EQUAL_PERIPHERALANGLES_EQUAL_ARCS_EQUAL_CHORDS, // 70
    EQUAL_ARCS_EQUAL_PERIPHERALANGLES, // 71
    PERIPHERALANGLE_ON_SAME_CHORD_FROM_SAME_SIDE_EQUAL, // 72
    PERIPHERALANGLE_ON_DIAMETER_RIGHT, // 73
    RIGHT_PERIPHERALANGLE_IS_ON_DIAMETER, // 74
    INTIRIOR_ANGLE_IS_AVERAGE_OF_TRAPPED_ARCS, // 75
    EXTERIOR_ANGLE_IS_DIFF_OVER_2_OF_TRAPPED_ARCS, // 76
    // Also allowed
    PARALLELOGRAM_AREA_SIDE_PERPENDICULAR,
    TRIANGLE_AREA_SIDE_PERPENDICULAR,
    RHOMBUS_AREA_DIAGONALS,
    TRAPEZOID_AREA_SIDE_BASES,
    CIRCLE_AREA_RADIUS_SQUARED,
    CIRCLE_PERIMETER_2RADIUS
}
