using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SolverSubProject.Information;

public enum Reason
{
    // Allowed reasons at bagrut, in order.
    GIVEN,

    ADJACENT_ANGLES_180, // 1
    VERTEX_ANGLES_EQUAL, // 2
    TRIANGLE_EQULA_SIDES_EQUAL_ANGLES, // 3
    ISOSCELES_BASE_ANGLES_EQUAL, // 4
    TRIANGLE_SUM_TWO_SIDES_LARGER_THIRD, // 5
    ISOSCELES_PERPENDICUAL_ANBISECTOR_ANGLE, // 6
    TRIANGLE_ANBISECTOR_PERPENDICULAR_IS_ISOSCELES, // 7
    TRIANGLE_ANBISECTOR_BISECTOR_IS_ISOSCELES, // 8
    TRIANGLE_PERPENDICULAR_BISECTOR_IS_ISOSCELES, // 9
    TRIANGLE_LARGER_SIDE_LARGER_ANGLE, // 10
    TRIANGLE_LARGER_ANGLE_BIGGER_SIDE, // 11
    TRIANGLE_ANGLE_SUM_180, // 12
    OUTSIDE_ANGLE_TWO_OTHER_TRIANGLE_ANGLES, //13
    MIDSEGMENT_PARALLEL_OTHER_TRIANGLE_SIDE, // 14
    LINE_BISECTS_SIDE_PARALLEL_OTHER_BISECTS_THIRD, // 15
    LINE_INTERSECTS_SIDES_PARALLEL_THRID_HALF_THIRD_LENGTH_IS_MIDSEGMENT, // 16
    CONGRUENT_S_A_S, // 17
    CONGRUENT_A_S_A, //18
    CONGRUENT_S_S_S, // 19
    CONGRUENT_S_S_A, // 20
    KITE_MAIN_DIAGONAL_BISECTS_ANGLE_BISECTS_DIAGONAL, // 21
    CORRESPONDING_ANGLES_EQUAL_LINES_PARALLEL, // 22
    ALTERNATE_ANGLES_EQUAL_LINES_PARALLEL, // 23
    COINTERIOR_ANGLES_180_LINES_PARALLEL, // 24
    CORRESPONDING_ANGLES_EQUAL, // 25 A
    ALTERNATE_ANGLES_EQUAL, // 25 A
    COINTERIOR_ANGLES_180, // 25 A

    // Also allowed
    PARALLELOGRAM_AREA_SIDE_PERPENDICULAR,
    TRIANGLE_AREA_SIDE_PERPENDICULAR,
    RHOMBUS_AREA_DIAGONALS,
    TRAPEZOID_AREA_SIDE_BASES,
    CIRCLE_AREA_RADIUS_SQUARED,
    CIRCLE_PERIMETER_2RADIUS
}
